HuyTuongShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('', include("home.urls")),
    path('user/', include("user.urls")),
    path('manage-product/', include("products.urls")),
    path('order/', include("order.urls")),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("detail/<str:slug>", views.DetailProduct.as_view(), name="detail"),
    path("search/", views.Search.as_view(), name="search"),
]

user/forms.py
from django import forms
from . import models
from django.utils import timezone
import re


class RegisterForm(forms.ModelForm):
    class Meta:
        model = models.MyUser
        fields = ("username", "password", "first_name", "last_name", "sex", "date_of_birth", "email", "phone",
                  "address", "avatar")
        widgets = {
            "date_of_birth": forms.SelectDateWidget(years=range(timezone.datetime.today().year - 100,
                                                                timezone.datetime.today().year)),
            "address": forms.Textarea(attrs={"rows": "3", "placeholder": "Số nhà, quận (huyện), tỉnh (thành phố)"}),
            "username": forms.TextInput(attrs={"placeholder": "Nhập tên đăng nhập"}),
            "password": forms.PasswordInput(attrs={"placeholder": "Mật khẩu"}),
            "email": forms.EmailInput(attrs={"placeholder": "Nhập địa chỉ email"}),
            "first_name": forms.TextInput(attrs={"placeholder": "Minh"}),
            "last_name": forms.TextInput(attrs={"placeholder": "Nguyễn Văn"}),
            "phone": forms.TextInput(attrs={"placeholder": "09094509"}),
        }

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]
        if not first_name:
            raise forms.ValidationError("Bạn không được để trống trường tên")
        if not "".join(first_name.split()).isalpha():
            raise forms.ValidationError("Tên chỉ được phép chứa các chữ cái")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]
        if not last_name:
            return last_name
        if not "".join(last_name.split()).isalpha():
            raise forms.ValidationError("Họ và tên lót chỉ được phép chứa các chữ cái")
        return last_name

    def clean_password(self):
        password = self.cleaned_data["password"]
        if not len(password) > 10:
            raise forms.ValidationError("Mật khẩu phải dài hơn 10 kí tự")
        if " " in password:
            raise forms.ValidationError("Mật khẩu không được chứa khoảng trắng")
        return password

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if not phone:
            return phone
        if not re.match("^[0-9+]*$", phone):
            raise forms.ValidationError("Số điện thoại chỉ có thể chưa chữ số và kí tự +")
        return phone

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UpdateProfileForm(forms.Form):
    first_name = forms.CharField(required=True, max_length=255,
                                 widget=forms.TextInput(attrs={"class": "form-control input-md"}))
    last_name = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={"class": "form-control input-md"}))
    phone = forms.CharField(max_length=15, required=False, widget=forms.TextInput(attrs={"class": "form-control input-md"}))
    email = forms.EmailField(required=False, widget=forms.EmailInput(attrs={"class": "form-control input-md"}))
    address = forms.CharField(required=False,
                              widget=forms.Textarea(attrs={"class": "form-control input-md", "rows": "3"}))
    password = forms.CharField(required=False, widget=forms.PasswordInput(attrs={"class": "form-control input-md"}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control input-md"}))
    sex = forms.IntegerField(
        widget=forms.Select(choices=((0, "Không xác định"), (1, "Nam"), (-1, "Nữ")), attrs={"class": "form-control"}))
    date_of_birth = forms.DateField(widget=forms.SelectDateWidget(
        years=range(timezone.datetime.today().year - 100, timezone.datetime.today().year),
        months={
            1: "Tháng một",
            2: "Tháng hai",
            3: "Tháng ba",
            4: "Tháng tư",
            5: "Tháng năm",
            6: "Tháng sáu",
            7: "Tháng bảy",
            8: "Tháng tám",
            9: "Tháng chín",
            10: "Tháng mười",
            11: "Tháng mười một",
            12: "Tháng mười hai",
        },
        attrs={"class": "form-control"}), )

    # Validate

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]
        if not first_name:
            raise forms.ValidationError("Bạn không được để trống trường tên")
        if not "".join(first_name.split()).isalpha():
            raise forms.ValidationError("Tên chỉ được phép chứa các chữ cái")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]
        if not last_name:
            return last_name
        if not "".join(last_name.split()).isalpha():
            raise forms.ValidationError("Họ và tên lót chỉ được phép chứa các chữ cái")
        return last_name

    def clean_password(self):
        password = self.cleaned_data["password"]
        if not len(password) > 10 and password != "":
            raise forms.ValidationError("Mật khẩu phải dài hơn 10 kí tự")
        if " " in password:
            raise forms.ValidationError("Mật khẩu không được chứa khoảng trắng")
        return password

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if not phone:
            return phone
        if not re.match("^[0-9]*$", phone) or phone[0] != "0":
            raise forms.ValidationError("Số điện thoại không hợp lệ")
        return phone


class AvatarForm(forms.Form):
    avatar = forms.ImageField()

templates/base/asideprofile.html
<div class="profile-sidebar">
    <!-- SIDEBAR USERPIC -->
    <div class="profile-userpic">
        <img src="{{ user.avatar.url }}" class="img-responsive" alt="">
    </div>
    <!-- END SIDEBAR USERPIC -->
    <!-- SIDEBAR USER TITLE -->
    <div class="profile-usertitle">
        <div class="profile-usertitle-name">
            {{ user.get_full_name }}
        </div>
        <div class="profile-usertitle-job">
            {{ user.username }}
        </div>
    </div>
    <!-- END SIDEBAR USER TITLE -->
    <!-- SIDEBAR BUTTONS -->
    <div class="profile-userbuttons">
        <form action="/user/profile/updateavatar/" method="post" enctype="multipart/form-data" id="formAvatar" >
            {% csrf_token %}
            <input type="file" name="avatar" accept="image/*" required="" id="id_avatar" class="d-none">
        </form>
        <button type="button" class="btn btn-success btn-sm" onclick="$('#id_avatar').click()">ĐỔI AVATAR</button>
        <button type="button" class="btn btn-danger btn-sm">BUTTON 2</button>
    </div>
    <!-- END SIDEBAR BUTTONS -->
    <!-- SIDEBAR MENU -->
    <div class="profile-usermenu">
        <ul class="nav">
            <li>
                <a href="/user/profile/">
                    <i class="glyphicon glyphicon-user"></i>
                    Thông tin tài khoản </a>
            </li>
            <li>
                <a href="/user/profile/edit/">
                    <i class="fas fa-user-edit"></i>
                    Chỉnh sữa thông tin </a>
            </li>
            <li>
                <a href="/order/selling/">
                    <i class="glyphicon glyphicon-ok"></i>
                    Đơn hàng </a>
            </li>
            <li>
                <a href="/order/my-order">
                    <i class="fas fa-shopping-cart"></i>
                    Giỏ hàng </a>
            </li>
            <li>
                <a href="/user/profile/shop/">
                    <i class="fas fa-store"></i>
                    Gian hàng của tôi </a>
            </li>
        </ul>
    </div>
    <!-- END MENU -->
</div>
<script type="text/javascript"
            src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.14.1/js/jquery.min.js"></script>
<script>
    $("#id_avatar").on("change", () => {
        let form = $('#formAvatar')[0]
        data = new FormData(form)
        $.ajax({
                type: "POST",
                url: '/user/profile/updateavatar/',
                processData: false,  // Important!
                contentType: false,
                cache: false,
                data: data,
                success: function (response) {
                    if (response["result"] == "OK"){
                        window.location.replace($(location).attr("href"));
                    } else {
                        alert("Đã xảy ra lỗi! Vui lòng thử lại sau")
                    }
                }
        });
    })
</script>

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/header.css" %}">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="shortcut icon" href="{% static "img/fav.png" %}"/>
    <link rel="stylesheet" href="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.14.1/css/mdb.min.css">
    <script src="https://kit.fontawesome.com/038c384707.js"></script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>

<body>
<!--Header-->
<header>
    <div class="container">
        <div class="header-top">
            <div class="header-top-left">
                <a href="#">Kênh người bán</a>
                <a href="#">Tải ứng dụng</a>
                <a href="#" class="border-none">Kết nối</a>
                <a href="#" class="border-none"><i class="fab fa-facebook"></i></a>
                <a href="#" class="border-none"><i class="fab fa-instagram"></i></a>
            </div>
            <div class="header-top-right">
                    <span><i class="far fa-bell"></i>
                        Thông báo</span>
                <span><i class="far fa-question-circle"></i>
                        Trợ giúp</span>
                {% if not user.is_authenticated %}
                    <span id="login" data-toggle="modal" data-target="#modalLoginForm">Đăng nhập</span>
                    <span id="register"><a href="/user/register">Đăng ký</a></span>
                {% else %}
                    <span>
                            <img class="avatar" src="{{ user.avatar.url }}">
                            <a href="/user/profile">{{ user.get_full_name }}</a>
                        </span>
                    <span><a href="/user/logout">Đăng xuất</a></span>
                {% endif %}
            </div>
        </div>
        <div class="header-bottom">
            <div class="logo">
                <img src="{% static "img/logo.png" %}" height="50" alt="logo">
            </div>
            <div class="search">
                <div class="search-input">
                    <form class="position-relative" action="/search">
                        <input class="key-search" name="q" type="text" placeholder="Tìm cái quái j củng được">
                        <button type="submit" class="position-absolute submit-search">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>
                <div class="tag">
                    <ul>
                        <li><a href="#">Dép Lào</a></li>
                        <li><a href="#">Dép </a></li>
                        <li><a href="#">Dép Campuchia</a></li>
                        <li><a href="#">Dép Bruney</a></li>
                    </ul>
                </div>
            </div>
            <div class="cart">
                <a href="/order/my-order">
                    <span><i class="fas fa-shopping-cart"></i></span>
                </a>
            </div>
        </div>
    </div>
</header>
<!--End header-->
<!--Form login-->
{% if not user.is_authenticated %}
    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100 font-weight-bold">Sign in</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="formLogin" class="loginForm" action="/user/login/" method="POST">
                    {% csrf_token %}
                    <div class="modal-body mx-3">
                        <div class="md-form mb-5">
                            <i class="fas fa-envelope prefix grey-text"></i>
                            <input type="text" name="username" id="defaultForm-email" class="form-control">
                            <label data-error="wrong" data-success="right" for="defaultForm-email">Tên đăng nhập</label>
                        </div>

                        <div class="md-form mb-4">
                            <i class="fas fa-lock prefix grey-text"></i>
                            <input type="password" name="password" id="defaultForm-pass" class="form-control">
                            <label data-error="wrong" data-success="right" for="defaultForm-pass">Mật khẩu</label>
                        </div>

                    </div>
                    <h6 class="text-danger text-center" id="errorLogin"></h6>
                    <div class="modal-footer d-flex justify-content-center">
                        <button class="btn btn-default" type="button" onclick="LoginAction()">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript"
            src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.14.1/js/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.14.1/js/bootstrap.min.js"></script>
    <script type="text/javascript"
            src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.14.1/js/mdb.min.js"></script>
    <script>
        function LoginAction() {
            $.ajax({
                type: "POST",
                url: '/user/login/',
                data: $('#formLogin').serialize(),
                success: (response) => {
                    if (response["result"] != "OK") return
                    if (response["message"] != "OK"){
                        $("#errorLogin").text(response["message"])
                        return
                    }
                    window.location.replace($(location).attr("href"))
                }
            });
    }
    </script>
{% endif %}
{% block body %}
{% endblock %}
<script type="text/javascript"
            src="https://mdbootstrap.com/api/snippets/static/download/MDB-Pro_4.14.1/js/jquery.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% block js %}
{% endblock %}
</body>

</html>

templates/base/category.html
<!--portfolio-->
<section class="portfolio">
    <div class="container">
        <h4 class="portfolio-title bg-white">Danh mục</h4>
        <div class="row list-portfolio bg-white">
            {% for item in category %}
                <div class="col-2">
                    <a class="d-inline-block w-100" href="/?category={{ item.slug_category }}">
                        <div class="wrapper-img-type">
                            <img class="img-categry position-absolute" src="/media/{{ item.image_category }}" alt="">
                        </div>
                        <h4 class="text-center">{{ item.name_category }}</h4>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/base/filter.html
<div class="form-row">
    <form id="filter-form" action="" class="form-row w-100">
        <div class="form-group col-md-4">
            <label for="inputState">Sắp xếp</label>
            <select id="order-by" name="order-by" class="form-control filter__select">
                <option value="time">Mới nhất</option>
                <option value="price-up">Giá tăng dần</option>
                <option value="price-down">Giá giảm dần</option>
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="inputState">Khuyến mãi</label>
            <select id="promotion" name="promotion" class="form-control filter__select">
                <option value="all">Tất cả</option>
                <option value="yes">Có khuyến mãi</option>
                <option value="no">Không khuyến mãi</option>
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="inputState">Tình trạng</label>
            <select id="available" name="available" class="form-control filter__select">
                <option value="all">Tất cả</option>
                <option value="yes">Còn hàng</option>
                <option value="no">Hết hàng</option>
            </select>
        </div>
    </form>
</div>

templates/base/list-product.html
{% load django_template_maths %}
<section class="product">
    <div class="container">
        <h4 class="bg-white title-section">Sản phẩm</h4>
        {% include "base/filter.html" %}
        <div class="row product-list">
            {% for item in products %}
                <div class="col-2 item-product">
                    <div class="product-item">
                        <img src="/media/{{ item.main_picture }}" class="product-img"
                             alt="">
                        <a href="/detail/{{ item.slug_product }}">
                            <p class="product-title">
                                {{ item.name_product }}
                            </p>
                        </a>
                        <span class="product-price">{{ 100|sub:item.discount|mul:item.price|div:100|separator:'comma' }}đ</span>
                        <span class="product-sold">Có sẵn: {{ item.num_available }}</span>
                        {% if item.discount != 0 %}
                            <span class="discount text-red">Discount {{ item.discount }}%</span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/base/slide.html
<section class="slide">
    <div class="container">
        <h2 class="text-center">SẢN PHẨM NỔI BẬT</h2>
        <div class="row">
            <div class="col-md-12">
                <div id="Carousel" class="carousel slide">
                    <ol class="carousel-indicators">
                        <li data-target="#Carousel" data-slide-to="0" class=""></li>
                        <li data-target="#Carousel" data-slide-to="1" class=""></li>
                        <li data-target="#Carousel" data-slide-to="2" class="active"></li>
                    </ol>
                    <!-- Carousel items -->
                    <div class="carousel-inner">
                        <div class="item">
                            <div class="row">
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://nhatminhdecor.com/wp-content/uploads/2019/03/chup-anh-san-pham-ngang-tam-san-pham.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://nhatminhdecor.com/wp-content/uploads/2019/01/39-chup-anh-san-pham.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://tech5s.com.vn/uploads/tintuc/9-loi-khuyen-khi-chup-anh-san-pham-tren-website-ban-hang-2-banner.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://adsplus.vn/wp-content/uploads/2019/02/chup-anh-san-pham-dep-xuat-sac-chi-voi-chiec-smartphone-1.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                            </div>
                            <!--.row-->
                        </div>
                        <!--.item-->
                        <div class="item">
                            <div class="row">
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://nhatminhdecor.com/wp-content/uploads/2019/03/chup-anh-san-pham-ngang-tam-san-pham.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://nhatminhdecor.com/wp-content/uploads/2019/01/39-chup-anh-san-pham.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://tech5s.com.vn/uploads/tintuc/9-loi-khuyen-khi-chup-anh-san-pham-tren-website-ban-hang-2-banner.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://adsplus.vn/wp-content/uploads/2019/02/chup-anh-san-pham-dep-xuat-sac-chi-voi-chiec-smartphone-1.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                            </div>
                            <!--.row-->
                        </div>
                        <!--.item-->
                        <div class="item active">
                            <div class="row">
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://nhatminhdecor.com/wp-content/uploads/2019/03/chup-anh-san-pham-ngang-tam-san-pham.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://nhatminhdecor.com/wp-content/uploads/2019/01/39-chup-anh-san-pham.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://tech5s.com.vn/uploads/tintuc/9-loi-khuyen-khi-chup-anh-san-pham-tren-website-ban-hang-2-banner.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                                <div class="col-md-3"><a href="#" class="thumbnail"><img
                                        src="https://adsplus.vn/wp-content/uploads/2019/02/chup-anh-san-pham-dep-xuat-sac-chi-voi-chiec-smartphone-1.jpg"
                                        alt="Image" style="max-width:100%;"></a>
                                </div>
                            </div>
                            <!--.row-->
                        </div>
                        <!--.item-->
                    </div>
                    <!--.carousel-inner-->
                    <a data-slide="prev" href="#Carousel" class="left carousel-control">‹</a> <a data-slide="next"
                                                                                                 href="#Carousel"
                                                                                                 class="right carousel-control">›</a>
                </div>
                <!--.Carousel-->
            </div>
        </div>
    </div>
</section>